GET http://localhost:4000/localhost:4000/pedidos/adicionar HTTP/1.1
//Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwiaWF0IjoxNjY5MjI4ODI1fQ.QEGVde2T3hfsmHS-be1ku-zMjwOotPRcD6YcqbUnEj8
Content-Type: application/json

{
    "Valor": 100,
    "MetPag": "Dinheiro",
    "ProdutosPedidos": [
        {
            "IdProduto": 1,
            "Quantidade": 2
        },
    ]
}